export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/plaza/index',
    'pages/events/index',
    'pages/market/index',
    'pages/topics/index',
    'pages/topic-detail/index',
    'pages/ranking/index',
    'pages/mine/index',
    'pages/login/index',
    'pages/community-select/index',
    'pages/event-detail/index',
    'pages/market-detail/index',
    'pages/event-create/index',
    'pages/market-create/index',
    'pages/notifications/index',
    'pages/profile-edit/index',
    'pages/badges/index',
    'pages/event-edit/index',
    'pages/market-edit/index',
    'pages/votes/index',
    'pages/vote-detail/index',
    'pages/committee/index',
    'pages/committee-member/index',
    'pages/committee-announcement/index',
    'pages/verify/index',
    'pages/settings/index',
    'pages/service-providers/index',
    'pages/service-provider-detail/index',
    'pages/social-groups/index',
  ],
  tabBar: {
    color: '#7A7A7A',
    selectedColor: '#35E89A',
    backgroundColor: '#FFF8EC',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/plaza/index',
        text: '小区广场',
        iconPath: 'assets/tab-plaza.png',
        selectedIconPath: 'assets/tab-plaza-active.png',
      },
      {
        pagePath: 'pages/topics/index',
        text: '议事榜',
        iconPath: 'assets/tab-topics.png',
        selectedIconPath: 'assets/tab-topics-active.png',
      },
      {
        pagePath: 'pages/ranking/index',
        text: '好人榜',
        iconPath: 'assets/tab-ranking.png',
        selectedIconPath: 'assets/tab-ranking-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'assets/tab-mine.png',
        selectedIconPath: 'assets/tab-mine-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFF8EC',
    navigationBarTitleText: '小区帮榜棒',
    navigationBarTextStyle: 'black',
  },
});
